import { library } from "@fortawesome/fontawesome-svg-core";
import * as regularIcon from "@fortawesome/free-regular-svg-icons";
import * as solidIcon from "@fortawesome/free-solid-svg-icons";
const icons = {
  faEye: regularIcon.faEye,
  faPenToSquare: regularIcon.faPenToSquare,
  faTrashCan: regularIcon.faTrashCan,
  faBarsProgress: solidIcon.faBarsProgress,
  faCalendar: solidIcon.faCalendar,
  faReceipt: solidIcon.faReceipt,
  faRightLeft: solidIcon.faRightLeft,
  faBell: solidIcon.faBell,
  faUser: solidIcon.faUser,
  faRightToBracket: solidIcon.faRightToBracket,
  faRectangleList: solidIcon.faRectangleList,
  faCircleUser: solidIcon.faCircleUser,
  faGear: solidIcon.faGear,
  faXmark: solidIcon.faXmark,
  faClock: solidIcon.faClock,
  faVault: solidIcon.faVault,
  faChartSimple: solidIcon.faChartSimple,
  faSackDollar: solidIcon.faSackDollar,
  faCheck: solidIcon.faCheck,
  faEllipsisVertical: solidIcon.faEllipsisVertical,
  faArrowUp: solidIcon.faArrowUp,
  faCode: solidIcon.faCode,
  faCartShopping: solidIcon.faCartShopping,
  faCreditCard: regularIcon.faCreditCard,
  faUnlockKeyhole: solidIcon.faUnlockKeyhole,
  faBarsStaggered: solidIcon.faBarsStaggered,
  faRegularClock: regularIcon.faClock,
  faWifi: solidIcon.faWifi,
  faBuildingColumns: solidIcon.faBuildingColumns,
  faWallet: solidIcon.faWallet,
  faPencil: solidIcon.faPencil,
  faPlus: solidIcon.faPlus,
  faFilePdf: solidIcon.faFilePdf,
  faCalendarDays: solidIcon.faCalendarDays,
  faArrowDown: solidIcon.faArrowDown,
  faExclamation: solidIcon.faExclamation,
  faCircleExclamation: solidIcon.faCircleExclamation,
};

library.add(icons);
